### ISSUE TITLE
코틀린 DSL을 이용한 Spring Rest Docs 쉽게 사용하기

### ISSUE THREAD

**Issue by yudonggeun** [kSideProject/kpring#10]
## :x: 문제점
Spring Rest Docs를 이용해서 문서화를 진행시에 코드를 파악하기 힘들다는 문제가 있었습니다.
![image](https://github.com/kSideProject/kpring/assets/67232422/51200a79-74e3-462a-a210-a063a4c54395)
다음 그림에서 보이는 기존의 코드를 코틀린을 이용해서 DSL을 설계하여

![image](https://github.com/kSideProject/kpring/assets/67232422/b18cfd7f-865d-4b7a-a107-a5ac4b38a26b)
다음 그림처럼 간단하게 문서를 정의할 수 있도록 하는 것을 목표로 진행합니다.

### 1. 공통 모듈에서 test 관련 의존성이 불편함
공통적으로 많이 사용하는 기능이라는 생각이 들어서 `core`모듈에서 구현을 하는 도중에 운영 코드에서 사용되지 않은 테스트 관련 소스를 임포트하는 것이 좋지 않다는 생각을 해서 test 관련 모듈을 관리하는 test 모듈을 새로 생성하여 개발을 진행합니다.

### 2. infix 함수를 통한 가독성 향상
자주 사용되는 기능에 대해서 infix 함수를 사용하면 가독성 측면에서 이점이 있을 것이라는 생각에 구현을 했습니다.

* 구현 빌더
![image](https://github.com/kSideProject/kpring/assets/67232422/5813e3e6-53f4-4625-b020-1bafd399163c)
* 사용 예시
![image](https://github.com/kSideProject/kpring/assets/67232422/3cbcf562-c317-4fc5-828e-9d3fc83059f1)

### 3. builder를 이용한 DSL 구현
builder를 이용해서 fluent API를 구현하여 직관적이고 더 적은 코드로 문서를 만들도록 구현하게 되었습니다.
구현 과정 중에서 document() 함수의 반환 타입을 추론하지 못하여 컴파일 에러가 발생하는 경우가 있었습니다.
이 때의 원인은 WebTestClient.consumeWith()의 파라미터로 입력하여서 타입이 추론이 가능하지만 이를 분리하여 구현하려 했기 때문에 발생하는 에러였습니다.

* 에러 발생 상황
![image](https://github.com/kSideProject/kpring/assets/67232422/1f91f3cf-cd82-4743-bdd0-6c38d6033496)
* 해결 방식 적용
![image](https://github.com/kSideProject/kpring/assets/67232422/eed1f80a-a287-4497-9694-118c4d608856)

## :white_check_mark: 끝으로
- 아직 모든 기능에 대해서 구현한 것이 아니기 때문에 제약이 있을 수 있지만 추후 요구사항을 반영하겠습니다.
- `WebTestClient`에서만 DSL을 제공하기 때문에 MVC에서 사용한다면 확장을 해야 사용이 가능합니다. 현재로서는 `WebTestClient`를 이용해서 테스트를 작성해주세요.

## 🔗 Reference
[Spring Rest Doc 공식 문서](https://docs.spring.io/spring-restdocs/docs/current/reference/htmlsingle/)
[toss spring rest doc 적용기](https://toss.tech/article/kotlin-dsl-restdocs)
issue #11

**Comment by minisundev** [comment]
👍와 너무 좋습니다!!
