### ISSUE TITLE
[추가기능 / API요청] Server생성과 Server조회 관련 API 요청

### ISSUE THREAD

**Issue by jihyun-j** [kSideProject/kpring#159]
### 서버생성에 필요한 API
현재 API에 ServerName만 존재하기 때문에 몇 가지 더 아래와 같이 요청 드립니다.
- 서버 카테고리(Category)
- 서버 호스트(Server Host): 서버 생성될 때 현재 로그인한 유저의 id값을 기본값으로 둘 예정입니다~
- 맵 테마(Theme)

### 서버 조회에 필요한 API
서버 조회에는 현재 서버Id, name, bookmarked가 존재하는데 아래와 같이 추가 요청 드립니다
- 서버 카테고리(Category)
- 서버 호스트(Server Host)
- 서버 단건 조회에 혹시 users는 어떻게 만들어지나요? 배열로 ["userId1", "userId2", "userId3"] 형식으로 나열 되나요? 

## 작업 상세 내용
- [x] 서버 단건 조회시 응답 users 스키마 갱신
- [x] 서버 단건 조회시 응답 owner 유저 데이터 스키마 확장
- [x] 서버 생성 요청시 userId 명시하도록 개선
- [x] 서버 생성시 카테고리 입력 (0 ~ 5개)
- [x] 서버 생성시 맵 테마 입력

## 참고할만한 자료(선택)
피그마에 와이어프레임 그려뒀습니다!

![Screenshot 2024-06-06 at 6 04 21 PM](https://github.com/kSideProject/kpring/assets/80092348/febd8ef7-b3fe-43c8-8d50-d26fdaea12fb)

**Comment by yudonggeun** [comment]
추후에 카테고리를 통해서 서버를 조회하는 기능이 필요하게 될까요?

**Comment by yudonggeun** [comment]
> 서버 단건 조회에 혹시 users는 어떻게 만들어지나요? 배열로 ["userId1", "userId2", "userId3"] 형식으로 나열 되나요?
```
{
  "id": user id 식별자,
  "name": 서버 프로필의 유저 이름,
  "profileImage": 저장한 프로필의 이미지
}
```
다음 json 객체를 배열로 반환하도록 구현했습니다.
