### ISSUE TITLE
build 했을 시 Java compatibility가 다르게 나타나는 현상

### ISSUE THREAD

**Issue by minisundev** [kSideProject/kpring#38]
## :x: 문제점
build를 했더니 다음과 같이 나왔습니다
![image](https://github.com/kSideProject/kpring/assets/58019747/4fe113b5-9ef9-45d9-94ac-b210ef783850)

> Task :test:compileKotlin
w: file:///D:/kopring-copy/test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBuilder.kt:28:5 Parameter 'description' is never used

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':auth:compileKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileJava' (22) and 'compileKotlin' (21).

  Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
  Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation

**Comment by yudonggeun** [comment]
https://discuss.kotlinlang.org/t/why-compilekotlin-cant-find-dependencies/19241
위에서 비슷한 상황에서 에러가 발생하는 것을 참고해서 원인을 추측했는데요.

## 원인
authClient를 코틀린 프로젝트에서 컴파일이 되지 않은 원인은 AuthClient가 java 파일이기 때문이였습니다.
`compileKotlin` 테스크에서 `Unresolved reference` 메시지를 호출하는 것을 확인했습니다. 이후에 AuthClient를 java -> kotlin으로 변경할 결과 정상적으로 빌드가 잘되는 것을 확인했어요.

하지만 자바 기반의 다른 도구들을 사용하는 것이 가능해야하는데 왜 안되는지 알아보았는데요
https://kotlinlang.org/docs/gradle-configure-project.html#targeting-the-jvm

자바는 `javac` 컴파일러를 통해서 `class`파일로 컴파일되는데요. 이 과정은 gradle의 `compileJava` 테스트에서 담당을 하고 있었어요. 
코틀린은 'kotlinc` 이라는 코틀린 전용 컴파일러를 통해서 `class`로 컴파일을 하고 이 과정은 `compileKotlin` 테스크에서 실행이 된다고 하더라구요.

근데 src/main/kotlin에 존재하는 모든 소스는 `kotlinc` 컴파일러 컴파일을 하게 되는데 여기에 자바 파일이 있다면 컴파일이 실패하게 되는 현상이 발생하는 것이었어요. 

## 해결
그래서 자바를 코틀린으로 통합을 하는 방식을 AuthClient에 적용하여 버그를 픽스하거나
`java` 디렉터리로 변경을 하는 방식이 있습니다.

**Comment by yudonggeun** [comment]
#38 PR로 픽스했습니다.

**Comment by minisundev** [comment]
원인을 알게 되어서 좋네요!!
