### ISSUE TITLE
[Chat] 채팅 조회 API 구현 : GET /api/v1/chat 

### ISSUE THREAD

**Issue by minisundev** [kSideProject/kpring#43]
## 어떤 기능인가요?

채팅을 조회하는 기능입니다.

## 작업 상세 내용

- [x] 채팅 조회 API 구현
- [x] 조회 권한 검증 부분 추가
- [x] 채팅 조회 테스트코드 작성

**Comment by yudonggeun** [comment]
제가 조회 기능 구현할께요!
