### ISSUE TITLE
[Chat] 채팅 조회 API 구현 : GET /api/v1/chat

### ISSUE THREAD

**Issue by minisundev** [kSideProject/kpring#52]
## 어떤 기능인가요?

채팅방 별로 채팅을 조회하는 기능입니다
🚧이슈 작성중~ 🚧

## 작업 상세 내용

- [ ] todo
- [ ] todo

**Comment by yudonggeun** [comment]
#43 과 중복된 이슈라서 close하겠습니다.

**Comment by minisundev** [comment]
부활..! 오늘 안에 살려야한다...1!!

**Comment by yudonggeun** [comment]
민선님 이거 #43 이랑 중복이라서 닫은거에요;;; #43 도 민선님이 만드신 거..

**Comment by minisundev** [comment]
> 민선님 이거 #43 이랑 중복이라서 닫은거에요;;; #43 도 민선님이 만드신 거..

오잉 그렇지만 이것은 이슈이고 저것은 PR인데요? ?

**Comment by yudonggeun** [comment]
#43 이것은 이슈고 #54 이게 PR 아닌가요?
